// The UI IR, emitted as Fusion.
//
// Roadmap 04, item 5, second target. The native exporter produces a tree; this
// one produces a tree that *reacts*, which is the only reason a second target
// is worth having. Two things it can do that a static tree cannot:
//
//   - **States render.** `states.hover` becomes an `OnEvent` pair driving a
//     `Value`, and every style property that differs between states becomes a
//     `Computed` over it. The native exporter can only carry them as attributes
//     for something else to interpret.
//   - **Bindings are live.** `binding.source` becomes a `Computed`, so the label
//     follows the value instead of being written once.
//
// Verified against `dphfox/Fusion@main` (v0.3-beta) rather than remembered,
// because 0.3 changed the API shape:
//
//   - `src/init.luau` exports `scoped`, `New`, `Children`, `OnEvent`, `Value`,
//     `Computed`, `peek`.
//   - `src/Instances/New.luau`: `New(scope, className)` returns a function
//     taking the property table — which is what makes `scope:New "Frame" {…}`
//     the idiomatic call.
//   - `src/Memory/scoped.luau`: `scoped(Fusion)` builds a cleanup table whose
//     methods are the constructors.
//
// A pre-0.3 Fusion has no scopes and would reject every line of this. The
// generated header says which version it targets rather than leaving that to be
// discovered at runtime.

import { resolveToken, validateScreen, type Style, type UiNode, type UiScreen } from './ir.js';

/** The Fusion release this generator targets. Stated in the output, not assumed. */
export const FUSION_TARGET = '0.3';

const CLASS_OF: Record<string, string> = {
  frame: 'Frame', text: 'TextLabel', button: 'TextButton',
  image: 'ImageLabel', input: 'TextBox', list: 'ScrollingFrame',
};

/** Property name in Roblox for each style field. */
const PROPERTY_OF: Partial<Record<keyof Style, string>> = {
  background: 'BackgroundColor3',
  foreground: 'TextColor3',
  border: 'BorderColor3',
  fontSize: 'TextSize',
};

/** The events that drive each interaction state, as Fusion `OnEvent` keys. */
const STATE_EVENTS: Record<string, { enter: string; leave: string }> = {
  hover: { enter: 'MouseEnter', leave: 'MouseLeave' },
  pressed: { enter: 'MouseButton1Down', leave: 'MouseButton1Up' },
};

export interface FusionModule {
  target: string;
  luau: string;
}

/**
 * Emit a Fusion component module.
 *
 * Refuses an invalid screen for the same reason the native exporter does: half
 * a UI looks like a bug in the design rather than a refusal to build one. And
 * it refuses a state this generator cannot drive rather than emitting a style
 * that silently never applies — a hover colour that never appears is harder to
 * notice than one that was never generated.
 */
export function exportFusion(screen: UiScreen): FusionModule {
  const verdict = validateScreen(screen);
  if (!verdict.ok) {
    const errors = verdict.issues.filter((i) => i.severity === 'error');
    throw new Error(`Cannot export ${screen?.id}: ${errors.length} error(s). First: ${errors[0].rule} — ${errors[0].message}`);
  }

  const undrivable = new Set<string>();
  collectUndrivableStates(screen.root, undrivable);
  if (undrivable.size > 0) {
    throw new Error(
      `Cannot export ${screen.id} to Fusion: no event drives ${[...undrivable].sort().join(', ')}. `
      + `This generator drives ${Object.keys(STATE_EVENTS).sort().join(' and ')}; a style for any other state would be emitted and never apply.`,
    );
  }

  const body: string[] = [];
  emitNode(screen, screen.root, body, 1, 'root');

  return {
    target: FUSION_TARGET,
    luau: [
      `-- Generated by BloxForge from the UI IR for screen "${screen.id}" (${screen.name}).`,
      `-- Targets Fusion ${FUSION_TARGET}. Earlier releases have no scopes and reject this.`,
      '-- Do not edit: regenerate from the IR.',
      'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
      'local Fusion = require(ReplicatedStorage.Packages.Fusion)',
      'local Children, OnEvent = Fusion.Children, Fusion.OnEvent',
      '',
      '-- `props` supplies whatever the IR bound: each binding.source is looked up',
      '-- here, so a missing one is a nil the component shows rather than a silent',
      '-- default nobody chose.',
      'return function(props, scope)',
      '\tscope = scope or Fusion.scoped(Fusion)',
      '\treturn ' + body.join('\n').trimStart(),
      'end',
      '',
    ].join('\n'),
  };
}

function collectUndrivableStates(node: UiNode, into: Set<string>): void {
  for (const state of Object.keys(node.states ?? {})) {
    if (!STATE_EVENTS[state]) into.add(state);
  }
  for (const child of node.children ?? []) collectUndrivableStates(child, into);
}

function emitNode(screen: UiScreen, node: UiNode, out: string[], depth: number, varName: string): void {
  const tab = '\t'.repeat(depth);
  const inner = '\t'.repeat(depth + 1);
  const states = Object.keys(node.states ?? {}).filter((s) => STATE_EVENTS[s]);
  const stateVar = `${sanitize(node.id)}State`;

  if (states.length > 0) {
    // One Value per node rather than one per state: the states are mutually
    // exclusive on a pointer, and two independent booleans would let a node be
    // hovered and not hovered at the same time.
    out.push(`${tab}(function()`);
    out.push(`${inner}local ${stateVar} = scope:Value("default")`);
    out.push(`${inner}return scope:New "${CLASS_OF[node.kind] ?? 'Frame'}" {`);
  } else {
    out.push(`${tab}scope:New "${CLASS_OF[node.kind] ?? 'Frame'}" {`);
  }

  const propIndent = states.length > 0 ? '\t'.repeat(depth + 2) : inner;
  const properties = propertyLines(screen, node, states, stateVar);
  for (const line of properties) out.push(`${propIndent}${line}`);

  for (const state of states) {
    const { enter, leave } = STATE_EVENTS[state];
    out.push(`${propIndent}[OnEvent "${enter}"] = function() ${stateVar}:set("${state}") end,`);
    out.push(`${propIndent}[OnEvent "${leave}"] = function() ${stateVar}:set("default") end,`);
  }

  const children = childLines(screen, node, depth + (states.length > 0 ? 2 : 1), varName);
  if (children.length > 0) {
    out.push(`${propIndent}[Children] = {`);
    out.push(...children);
    out.push(`${propIndent}},`);
  }

  if (states.length > 0) {
    out.push(`${inner}}`);
    out.push(`${tab}end)()`);
  } else {
    out.push(`${tab}}`);
  }
}

function propertyLines(screen: UiScreen, node: UiNode, states: string[], stateVar: string): string[] {
  const lines: string[] = [`Name = "${node.id}",`];
  const base = node.style ?? {};

  for (const [field, property] of Object.entries(PROPERTY_OF) as [keyof Style, string][]) {
    const perState = states.filter((s) => node.states?.[s as 'hover' | 'pressed']?.[field] !== undefined);
    if (perState.length === 0) {
      const value = literalFor(screen, field, base[field]);
      if (value) lines.push(`${property} = ${value},`);
      continue;
    }
    // Only the properties that actually differ become Computed. Wrapping every
    // property would make the whole tree re-evaluate on a mouse move.
    const branches = perState.map((s) => {
      const styled = node.states![s as 'hover' | 'pressed']![field];
      return `\t\tif state == "${s}" then return ${literalFor(screen, field, styled) ?? 'nil'} end`;
    });
    const fallback = literalFor(screen, field, base[field]) ?? 'nil';
    lines.push(
      `${property} = scope:Computed(function(use)`,
      `\t\tlocal state = use(${stateVar})`,
      ...branches,
      `\t\treturn ${fallback}`,
      '\tend),',
    );
  }

  if (node.binding?.property === 'content') {
    lines.push(`Text = scope:Computed(function(use) return use(props.${node.binding.source.replace(/\./g, '_')}) end),`);
  } else if (node.content !== undefined) {
    lines.push(`Text = ${JSON.stringify(node.content)},`);
  }
  if (node.binding?.property === 'visible') {
    lines.push(`Visible = scope:Computed(function(use) return use(props.${node.binding.source.replace(/\./g, '_')}) end),`);
  }

  lines.push(`Size = ${udim2For(node)},`);
  if (base.background === undefined) lines.push('BackgroundTransparency = 1,');
  if (node.layout?.order !== undefined) lines.push(`LayoutOrder = ${node.layout.order},`);
  if (node.accessibility?.focusOrder !== undefined) {
    lines.push('Selectable = true,', `SelectionOrder = ${node.accessibility.focusOrder},`);
  }
  return lines;
}

function childLines(screen: UiScreen, node: UiNode, depth: number, parentVar: string): string[] {
  const tab = '\t'.repeat(depth + 1);
  const lines: string[] = [];
  const style = node.style ?? {};

  const radius = style.radius && resolveToken(screen.tokens, style.radius);
  if (radius !== undefined) lines.push(`${tab}scope:New "UICorner" { CornerRadius = UDim.new(0, ${Number(radius)}) },`);

  const padding = style.padding && resolveToken(screen.tokens, style.padding);
  if (padding !== undefined) {
    const value = `UDim.new(0, ${Number(padding)})`;
    lines.push(`${tab}scope:New "UIPadding" { PaddingTop = ${value}, PaddingBottom = ${value}, PaddingLeft = ${value}, PaddingRight = ${value} },`);
  }

  if (node.layout?.direction) {
    const gap = style.gap && resolveToken(screen.tokens, style.gap);
    const fill = node.layout.direction === 'row' ? 'Horizontal' : 'Vertical';
    const padPart = gap === undefined ? '' : `, Padding = UDim.new(0, ${Number(gap)})`;
    lines.push(`${tab}scope:New "UIListLayout" { FillDirection = Enum.FillDirection.${fill}, SortOrder = Enum.SortOrder.LayoutOrder${padPart} },`);
  }

  for (const child of node.children ?? []) {
    const sub: string[] = [];
    emitNode(screen, child, sub, depth + 1, `${parentVar}_${sanitize(child.id)}`);
    // The last line of a child expression carries the comma that separates it
    // from its sibling inside the Children table.
    sub[sub.length - 1] = `${sub[sub.length - 1]},`;
    lines.push(...sub);
  }
  return lines;
}

function literalFor(screen: UiScreen, field: keyof Style, ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const value = resolveToken(screen.tokens, ref);
  if (value === undefined) return undefined;
  if (field === 'fontSize') return String(Number(value));
  const hex = String(value).replace('#', '');
  const channel = parseInt(hex, 16);
  return `Color3.fromRGB(${(channel >> 16) & 255}, ${(channel >> 8) & 255}, ${channel & 255})`;
}

function udim2For(node: UiNode): string {
  const layout = node.layout;
  const xScale = layout?.widthPx === undefined ? layout?.width ?? 1 : 0;
  const yScale = layout?.heightPx === undefined ? layout?.height ?? 1 : 0;
  return `UDim2.new(${xScale}, ${layout?.widthPx ?? 0}, ${yScale}, ${layout?.heightPx ?? 0})`;
}

/** Node ids are validated as unique but not as Luau identifiers. */
function sanitize(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(cleaned) ? cleaned : `n${cleaned}`;
}
